fix test e2e back

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -106,7 +106,7 @@ jobs:
       - name: ✅ Wait for Postgres
         run: |
           for i in {1..60}; do
-            if docker compose exec -T postgres pg_isready -U postgres -d lotodb > /dev/null 2>&1; then
+            if docker compose exec -T postgres pg_isready -U postgrestest -d lotodb_test > /dev/null 2>&1; then
               echo "✅ Postgres ready"
               exit 0
             fi
@@ -134,9 +134,9 @@ jobs:
 
 
 
-      - name: 📊 JaCoCo Report
-        # run: mvn -B jacoco:report
-        run: mvn -B clean verify jacoco:report
+      # - name: 📊 JaCoCo Report
+      #   run: mvn -B jacoco:report
+        # run: mvn -B clean verify jacoco:report
       # - name: 📊 Run tests + JaCoCo Report
       #   # run: mvn -B clean verify -Dspring.profiles.active=ci
       #   run: mvn -B clean verify jacoco:report
@@ -144,21 +144,45 @@ jobs:
         # run: mvn -B clean verify jacoco:report -Dspring.profiles.active=test
         # run: mvn -B clean verify -Dspring.profiles.active=ci
 
-      - name: 🔎 Debug JaCoCo files
+      - name: 📊 Run tests + JaCoCo
+        run: |
+            mvn -B clean verify \
+                -Dspring.profiles.active=ci
+      - name: 🔎 Debug JaCoCo
         if: always()
         run: |
-          pwd
-          ls -la
-          find . -path "*/target/site/jacoco/index.html" -print
-          find . -name "jacoco.exec" -print
+            echo "=== exec ==="
+            find . -name "*.exec"
+
+            echo "=== html ==="
+            find . -name "index.html" | grep jacoco || true
+
+            echo "=== target ==="
+            ls -lah target || true
+
+            echo "=== site ==="
+            ls -lah target/site || true
+
+            echo "=== jacoco ==="
+            ls -lah target/site/jacoco || true
+
+            echo "=== jacoco index ==="
+            cat target/site/jacoco/index.html >/dev/null && echo "✅ index.html exists" || echo "❌ index.html missing"
+
+      # - name: 🔎 Debug JaCoCo files
+      #   if: always()
+      #   run: |
+      #     pwd
+      #     ls -la
+      #     find . -path "*/target/site/jacoco/index.html" -print
+      #     find . -name "jacoco.exec" -print
       - name: 📤 Upload JaCoCo HTML Report
         if: always()
         uses: actions/upload-artifact@v4
         with:
           name: jacoco-report
-          path: |
-            target/site/jacoco/
-            **/target/site/jacoco/
+          path: target/site/jacoco/
+          retention-days: 30
 
       - name: 📝 JaCoCo Summary
         if: always()
@@ -178,10 +202,10 @@ jobs:
       - name: 🗃️ Wait for users table
         run: |
           for i in {1..60}; do
-            if docker compose exec -T postgres psql -U postgres -d lotodb -tAc \
+            if docker compose exec -T postgres psql -U postgrestest -d lotodb_test -tAc \
               "SELECT to_regclass('public.users');" | grep -q "users"; then
               echo "✅ users table exists"
-              docker compose exec -T postgres psql -U postgres -d lotodb -c \
+              docker compose exec -T postgres psql -U postgrestest -d lotodb_test -c \
                 "SELECT id,email,is_admin FROM public.users LIMIT 5;" || true
               exit 0
             fi
@@ -190,7 +214,8 @@ jobs:
           done
           echo "❌ users table never created"
           docker compose logs --no-color backend
-          docker compose exec -T postgres psql -U postgres -d lotodb -c "\dt" || true
+          # docker compose exec -T postgres psql -U postgres -d lotodb -c "\dt" || true
+          docker compose exec -T postgres psql -U postgrestest -d lotodb_test -c "\dt" || true
           exit 1
 
       # ✅ Tests API (on crée un user CI, puis login, puis on utilise le JWT)
@@ -265,7 +290,8 @@ jobs:
       - name: 🔧 Setup Node
         uses: actions/setup-node@v4
         with:
-          node-version: 20
+          # node-version: 20
+          node-version: 24
           cache: npm
 
       - name: 📦 Install npm dependencies
